name: CI/CD with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout & Build & Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            cd ui
            yarn install
            yarn build
            cd ${{ secrets.DEPLOY_PATH }}
            PORT=${{ secrets.DEPLOY_PATH }} nohup node ./server/dist/main.js  > /dev/null 2>&1 &
